security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: username

    role_hierarchy:
        ROLE_USER:    ROLE_USER
        ROLE_ADMIN:   ROLE_ADMIN

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   logout
                target: login
            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/tournament, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/match/add, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/match/update, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/match/delete, roles: [ROLE_USER, ROLE_ADMIN] }